### PR TITLE
Now using newline as line separator in all cases

### PR DESCRIPTION
**Pull request by Caesarovich**
Fixes issue #79

### CODE REVIEW

**Comment by Caesarovich** [comment]
@sindresorhus ;)

**Comment by sindresorhus** [comment]
Thanks for fixing 👍

**Comment by sindresorhus** [comment]
> Fixes issue https://github.com/sindresorhus/boxen/issues/79

You need to write `Fixes #79` so that GitHub automatically closes the issues.

**Comment by Caesarovich** [comment]
Okay thanks for the tip @sindresorhus ;)

**Pull request merged**
