### PR TITLE
Add link to CLI in the readme

### PR DESCRIPTION
**Pull request by icyflame**

### CODE REVIEW

**Comment by kevva** [comment]
Thanks!

**Comment by sindresorhus** [comment]
Please don't make CLI's for my modules. I prefer to do so myself so I can ensure high-quality. For this one I already had it made, but the publish step seem to have failed without me noticing. There's so many possible useful CLI's you could make instead of this. https://github.com/sindresorhus/module-requests/issues

Can I please have the npm name back so I can do it properly? :)

**Comment by icyflame** [comment]
@sindresorhus I am sorry, I thought I was helping out with a trivial step.

I have not published this module to the registry yet. So, you can go ahead and `npm publish` your module.

**Comment by sindresorhus** [comment]
Don't be sorry. You couldn't have known :) And sorry for the bluntness, I was on my phone. It's just a lot faster and easier for me to create the CLI's myself rather than sending a lot of PRs to fix them up.

od3vvoq

**Pull request merged**
