### PR TITLE
Prevent padding error for center alignment

### LINKED ISSUE #27: Boxen crashes on padding when terminal size < box size
When the box size exceeds the terminal size, `padWidth` turns into a negative value, which causes the `repeat` function to error:

```
const padWidth = (columns - contentWidth) / 2;
marginLeft = PAD.repeat(padWidth);
```

 We see this failure when using `center` alignment (our default) but not when `right` is used.

image

### PR DESCRIPTION
**Pull request by simonua**
@sindresorhus, fixes #27.

### CODE REVIEW

**Comment by marcjansen** [comment]
I cannot see the initially failing test. Is this just ne or is it actually missing?

**Comment by simonua** [comment]
Hi @marcjansen, the linter failed on formatting initially. I didn't think to run `npm test` locally or I would have seen it. Joke's on me since we use `npm test` in all of our work on my end, too....

**Comment by simonua** [comment]
I can look into adding a test for it hopefully later tonight.

**Comment by marcjansen** [comment]
No rush, take your time. Looking forward to reviewing again.

**Comment by simonua** [comment]
@marcjansen, you had the right idea on using `Math.max`. It bypassed me a bit that that's why the right-alignment worked. The `center` behavior now mirrors that same successful behavior on negative values defaulting to 0.

**Comment by simonua** [comment]
@marcjansen, the code works, but I'm not quite certain on whether this requires additional changes to the tests. If you don't mind, could you take a look and jump in if it requires modifications, please?

Danke!

**Comment by marcjansen** [comment]
I have added two tests.

One ensures that we do not throw when the content is bigger than the available columns (which is basically a regression test), and the second one ensures that we effectively ignore the float option if the content is bigger than the available columns (which is a test for the corrected behaviour).

What do you think @sindresorhus & @simonua ?

**Comment by simonua** [comment]
@marcjansen, your tests look good from my end. I like how you effectively combined multiple asserts into the same test in your second addition. I pulled down the code, ran `npm test` and verified coverage as well. All looks good.

**Comment by marcjansen** [comment]
Thanks for the feedback. Do you need 
have this merged quickly? And possibly released? If so, I can merge right now.

Otherwise I would like to have @sindresorhus have his say here.

**Comment by simonua** [comment]
Hi @marcjansen, not having this is presently a nuisance for us, so I would ask to have it released, but if you have any concerns about it at all or definitely want Sindre's feedback, I'm not opposed to waiting either. I know he's got a ton of packages and repos, so I'm not sure when he'll get to it.

**Comment by marcjansen** [comment]
Ok, I'll merge this then. Once @sindresorhus sees this, he may always make follow up PRs or even revert.

Once this is merged you can e.g. get it by referring the merge commit in the dependency section of your package.json. I don't think I habe the right to release this package to npm.

Anyhow, thanks for the fix you provided and the nice collaboration.

**Comment by simonua** [comment]
Vielen Dank, @marcjansen!

Appreciate the collaboration, too. Always nice to work with good folks.

**Comment by simonua** [comment]
Awesome, @sindresorhus! Thank you and @marcjansen VERY MUCH! I appreciate you.

Simon

**Comment by marcjansen** [comment]
👍

**Pull request merged**
