### PR TITLE
Allow border to be optional.

### LINKED ISSUE #84: Allow border to be optional.
This tool has a lot of great features for creating boxes, and some of those features would be nice on their own. For instance, fullscreen would be great in some cases even without a border.

My use case, however, incorporates boxen into another utility. In order to achieve "no border", I have given boxen a "ghost border" which I strip after boxen's done working.

```js
borderStyle: {
	topLeft: ' ',
	topRight: ' ',
	bottomLeft: ' ',
	bottomRight: ' ',
	top: ' ',
	bottom: ' ',
	left: ' ',
	right: ' '
}
```

### PR DESCRIPTION
**Pull request by Caesarovich**
Fixes #84

Fix not being able to specify empty strings in borderStyle options.

### CODE REVIEW

**Comment by Caesarovich** [comment]
@sindresorhus I propose this to be 7.0.3

**Comment by sindresorhus** [comment]
You have to update the readme and types too.

**Comment by Caesarovich** [comment]
@sindresorhus I'm not really sure what you mean by that. Empty strings are still of type string for TS so it does not change anything regarding the types from my point of view. Please let me know your thoughts.

**Comment by sindresorhus** [comment]
Your pull request title does not match the pull request description. Optional is not the same as empty string.

**Comment by Caesarovich** [comment]
@sindresorhus That needs investigation, I cannot replicate the test errors. I'm not sure what it is about.

**Comment by sindresorhus** [comment]
I will publish an update tomorrow.

**Pull request merged**
