### PR TITLE
Rework tests to use snapshots

### PR DESCRIPTION
**Pull request by Caesarovich**
This PR reworks the all the unit testing for this library into snapshot tests, as suggested by @sindresorhus . 
So first of all I deleted the old test.js file which was getting pretty long (800~ lines), and spitted it into multiple files in the 'tests' folder. This folder is organized into files corresponding to all the main options for the library. Thus each file contains unit tests relative to the option it is named upon. Tests aiming to determine if X option break Z option when combined together should be conducted in the Z file. So the Z file should test for all combination of options that could break Z, etc... (If don't know if I'm clear there but that's just picky).

So sorry in advance because this is going to be a pain to review since there's a lot of tests, files, and snapshots.

### CODE REVIEW

**Comment by Caesarovich** [comment]
It appears that GH tests failed. Did I mess up something or is directly related to the fact that I completely reworked the way the tests operates ?

**Comment by sindresorhus** [comment]
Run `npm install -d typescript` (it's a bug in XO)

**Comment by sindresorhus** [comment]
Are you sure you have covered everything that the old tests covered?

**Comment by Caesarovich** [comment]
> Are you sure you have covered everything that the old tests covered?

I'll detail it to you in this thread.

**Comment by Caesarovich** [comment]
test 1, 49 - 53: Into main.js
test 2 - 8: Into title-option.js
test 9 - 10: Into padding-option.js
test 11, 39-44: Into margin-option.js
test 12 - 19: Into float-option.js
test 20 - 33, 41: Into border-option.js
test 34 - 39, 45 - 48: Into text-align-option.js

Some separate tests have been merged into one, and I added some new tests too. (Like one checking for errors similar to #62 ).

**Comment by sindresorhus** [comment]
This is so much nicer. Thanks for doing this 👍

Would you be interested in becoming a maintainer on this project? You have done some great work. No worries if not though.

**Comment by Caesarovich** [comment]
> This is so much nicer. Thanks for doing this +1

Thanks you for the opportunity to work on this project ! This is my first real experience as "Contributor" on GitHub and it is really nice working with you !

> Would you be interested in becoming a maintainer on this project? You have done some great work. No worries if not though.

What does that imply specificaly ?

**Comment by sindresorhus** [comment]
> What does that imply specificaly ?

You really do whatever you want and what you have time for. For example, triage issues, review pull requests, etc. But there's no expectation of how much of this you do. Maintainer status is just to signify that you have more say in issues, etc, and you get your name in the readme.

**Comment by Caesarovich** [comment]
Sure thing then.

**Comment by sindresorhus** [comment]
Awesome! :)

I generally prefer using pull requests for new features / bug fixes as it's always good to get a second eye on things.

**Pull request merged**
