### PR TITLE
Smaller refactorings (more variables & fewer unneeded recalculations)

### PR DESCRIPTION
**Pull request by marcjansen**
This PR suggests some minor changes when generating the boxes:

* Add and use two variables for the often used strings `'\n'` & `' '`
* `paddingLeft` was recalculated for every line, but it's value is constant
* `marginLeft` is newly introduced

Please review.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Can you fix the merge conflict?

**Comment by marcjansen** [comment]
I will. But it'll need to wait 3 days...

**Comment by sindresorhus** [comment]
@marcjansen No rush :)

**Comment by marcjansen** [comment]
@sindresorhus rebased. TIA for another look.

**Comment by sindresorhus** [comment]
Looks good. Thanks :)

**Comment by sindresorhus** [comment]
Adding you to the repo since you've done some good PRs :)

https://github.com/Level/community/blob/master/CONTRIBUTING.md

**Comment by marcjansen** [comment]
Thanks!

**Pull request merged**
